# Generated by Django 4.1.2 on 2022-12-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Optimizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronym', models.CharField(help_text='Short name for the optimizer', max_length=10, verbose_name='Acronym')),
                ('name', models.CharField(help_text='Name of the optimizer', max_length=50, verbose_name='Name')),
            ],
        ),
    ]
