# Generated by Django 4.1.2 on 2022-12-15 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_optimizer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(help_text='Short name for the function', max_length=50, verbose_name='Short Name')),
                ('name', models.CharField(help_text='Name of the function', max_length=50, verbose_name='Name')),
                ('latex_expression', models.CharField(help_text='Latex expression for the function', max_length=255, verbose_name='Latex Expression')),
            ],
        ),
    ]
