# Generated by Django 4.1.3 on 2022-12-21 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_dataset_alter_function_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Transfer Function', max_length=50, verbose_name='Name')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
