# Generated by Django 4.1.3 on 2022-12-27 23:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_function_optimal_result_function_search_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferfunction',
            name='latex_expression',
            field=models.CharField(default=django.utils.timezone.now, help_text='Latex expression for the transfer function', max_length=255, verbose_name='Latex Expression'),
            preserve_default=False,
        ),
    ]
