# Generated by Django 4.1.2 on 2022-12-30 16:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_rename_optimal_result_function_optimal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='function',
            name='search_space',
        ),
        migrations.AddField(
            model_name='function',
            name='bound',
            field=models.TextField(default=django.utils.timezone.now, help_text='JSON representation of the bound', verbose_name='Bound'),
            preserve_default=False,
        ),
    ]
