# Generated by Django 4.1.3 on 2022-12-30 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_dataset_samples'),
        ('dashboard', '0010_remove_function_search_space_function_bound'),
    ]

    operations = [
    ]
